### ISSUE TITLE
when will put the model and code on the github?

### ISSUE THREAD

**Issue by jiatianzhi** [crisie/RecurrentGaze#1]

**Comment by crisie** [comment]
Dear jiatianzhi,

Thanks for your interest. The code will be ready in less than two weeks' time. Model will take a bit longer as we plan to re-train it so that we have one model for all the data, instead of one model per fold. It all should be ready by the end of this month. Please bear with me.

Cristina

**Comment by lucfisc** [comment]
Hi, where could we find the model ? Thanks

**Comment by crisie** [comment]
The model definitions are in the `models` folder, and the URLs of the model weights are in `experiments_utils.py`. When using the `Test` script, and given an experiment name as input parameter `-exp`, `experiments_helper.py` is in charge of loading the model definition and weights associated to that experiment. For instance, if you select NFEL5836 experiment, which corresponds to the static face+eyes+landmarks model, the script will select the `two_stream` model definition and the _NFEL5836_ weights. For more info please check the `__init__` methods of each ExperimentHelper subclass in `experiment_helper.py`, which correspond to the different experiments available.
