### ISSUE TITLE
one frame

### ISSUE THREAD

**Issue by JiaqiuZhou** [crisie/RecurrentGaze#3]
if I can test the model to estimate the gaze only input one frame?

**Comment by crisie** [comment]
Hi!

`Test.py` is the script devoted to perform gaze estimation. The current version of the code expects 3 input text files, as well as the image, with the following information of the image:
- **CCS_3D_info**: 3D information of the face (head pose and 3D landmarks) wrt the Camera Coordinate System. In the Test folder the example is computed with [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation); for instance, you can use their `OpenFaceOffline.exe` Windows executable to easily extract this information.
- **landmarks**: 3D landmarks from [Bulat et al. 2017](https://github.com/1adrianb/face-alignment). Their instructions are quite clear as well.
- **calibration**: camera matrix. If you don't have the camera parameters, you can use a dummy matrix like so:
```
[1.2*image_width, 0.0, image_width/2],
[0.0, 1.2*image_width, image_height/2],
[0.0, 0.0, 1.0]
```
You can follow the examples in the Test folder to check the required format. 

Anyway, I'm currently preparing a new version of the code which will have all the steps integrated, so that you just need to use one image as input and the code will compute all the necessary pre-processing steps as well as estimate gaze. It should be ready by mid July, so if you're in a hurry I suggest you try the current version, otherwise wait till the new one is out :). 

Best,
Cristina

**Comment by JiaqiuZhou** [comment]
ooooooooook! 
Thank you very much!
It had helped me a lot, and I can run in one frame now.
